title: Parchment
author: pro-panda
subtitle: The life of a frustrated engineer

url: "https://pro-panda.github.io"
baseurl: "/parchment"

footer_only_homepage: true
footer_url: "https://github.com/pro-panda"
footer_text: "Theme by pro-panda"

profile-picture: demo/profile.png
favicon_location: demo/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://pro-panda.github.io/resume.pdf"
